// Generated by scripts/import-product-feed.mjs. Do not edit manually.
import type { Product } from "../types";

export const verifiedProductFeedSync = {
  "sourceConfigured": false,
  "network": "awin",
  "importedCount": 0,
  "skippedCount": 0,
  "generatedAt": null,
  "message": "Set PRODUCT_FEED_URL or PRODUCT_FEED_FILE to import verified products."
} as const;

export const verifiedProducts: Product[] = [];
