import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: 1,
    brand: "The Row",
    name: "Cashmere Blend Wide-Leg Trousers",
    description:
      "Luxury wide-leg trousers in a cashmere-wool blend, tailored for refined quiet-luxury wardrobes.",
    price: 1190,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    ],
    category: "trousers",
    subcategory: "wide-leg trousers",
    colors: ["black"],
    materials: ["wool", "cashmere"],
    vibe: ["quiet luxury", "elegant", "minimalist"],
    style: ["minimalist", "clean", "classy"],
    occasion: ["dinner", "office", "formal"],
    season: ["winter", "autumn"],
    gender: ["women"],
    fit: ["wide leg", "tailored"],
    productUrl: "https://www.therow.com/products/cashmere-wide-leg-trousers",
    affiliateUrl: "https://socialmall.com/out/the-row-wide-leg-trousers",
    retailer: "The Row",
    inStock: true,
    featured: true,
    popularityScore: 97,
    shippingCountry: "IE",
    brandSlug: "the-row",
    productSlug: "cashmere-blend-wide-leg-trousers",
    rating: 4.8,
    reviewCount: 214,
  },
  {
    id: 2,
    brand: "Jacquemus",
    name: "Le Chouchou Draped Linen Shirt",
    description:
      "A draped linen shirt with resort tailoring and breathable structure for elevated summer dressing.",
    price: 520,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
    ],
    category: "shirt",
    subcategory: "linen shirt",
    colors: ["beige", "cream"],
    materials: ["linen"],
    vibe: ["marbella", "resort", "elegant"],
    style: ["resort", "smart casual", "minimalist"],
    occasion: ["holiday", "beach club", "dinner"],
    season: ["summer", "spring"],
    gender: ["men"],
    fit: ["relaxed"],
    productUrl: "https://www.jacquemus.com/products/le-chouchou-linen-shirt",
    affiliateUrl: "https://socialmall.com/out/jacquemus-linen-shirt",
    retailer: "Jacquemus",
    inStock: true,
    featured: true,
    popularityScore: 90,
    compareAtPrice: 590,
    shippingCountry: "IE",
    brandSlug: "jacquemus",
    productSlug: "le-chouchou-draped-linen-shirt",
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: 3,
    brand: "COS",
    name: "Relaxed Oversized Black Hoodie",
    description:
      "Heavyweight cotton hoodie with a dropped-shoulder oversized fit designed for modern streetwear layering.",
    price: 135,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=900&q=80",
    ],
    category: "hoodie",
    subcategory: "oversized hoodie",
    colors: ["black"],
    materials: ["cotton", "knit"],
    vibe: ["casual", "streetwear", "minimalist"],
    style: ["streetwear", "clean"],
    occasion: ["airport outfit", "casual"],
    season: ["winter", "autumn"],
    gender: ["unisex"],
    fit: ["oversized", "relaxed"],
    productUrl: "https://www.cos.com/en/oversized-black-hoodie",
    affiliateUrl: "https://socialmall.com/out/cos-black-hoodie",
    retailer: "COS",
    inStock: true,
    featured: true,
    popularityScore: 95,
    compareAtPrice: 165,
    shippingCountry: "IE",
    brandSlug: "cos",
    productSlug: "relaxed-oversized-black-hoodie",
    rating: 4.7,
    reviewCount: 488,
  },
  {
    id: 4,
    brand: "Toteme",
    name: "Minimalist Structured Wool Blazer",
    description:
      "A sharply cut wool blazer with minimalist lines for polished office and evening tailoring looks.",
    price: 790,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=900&q=80",
    ],
    category: "blazer",
    subcategory: "structured blazer",
    colors: ["black"],
    materials: ["wool"],
    vibe: ["quiet luxury", "elegant", "minimalist"],
    style: ["classy", "smart casual", "minimalist"],
    occasion: ["office", "formal", "dinner"],
    season: ["winter", "autumn", "spring"],
    gender: ["women"],
    fit: ["tailored"],
    productUrl: "https://toteme.com/products/structured-wool-blazer",
    affiliateUrl: "https://socialmall.com/out/toteme-wool-blazer",
    retailer: "Toteme",
    inStock: true,
    featured: false,
    popularityScore: 84,
    shippingCountry: "IE",
    brandSlug: "toteme",
    productSlug: "minimalist-structured-wool-blazer",
    rating: 4.7,
    reviewCount: 132,
  },
  {
    id: 5,
    brand: "Arket",
    name: "White Cotton Essential Tee",
    description:
      "A clean everyday cotton tee with a relaxed silhouette that anchors capsule wardrobes and casual fits.",
    price: 55,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80",
    ],
    category: "tshirt",
    subcategory: "crew neck t-shirt",
    colors: ["white"],
    materials: ["cotton"],
    vibe: ["casual", "minimalist"],
    style: ["clean", "minimalist"],
    occasion: ["casual", "airport outfit"],
    season: ["summer", "spring"],
    gender: ["men"],
    fit: ["relaxed"],
    productUrl: "https://www.arket.com/en/cotton-essential-tee",
    affiliateUrl: "https://socialmall.com/out/arket-essential-tee",
    retailer: "Arket",
    inStock: true,
    featured: false,
    popularityScore: 88,
    compareAtPrice: 65,
    shippingCountry: "IE",
    brandSlug: "arket",
    productSlug: "white-cotton-essential-tee",
    rating: 4.5,
    reviewCount: 812,
  },
  {
    id: 6,
    brand: "Aeyde",
    name: "Leather Slip-On Sandals",
    description:
      "Minimal leather slip-on sandals with soft neutral tones for beach club and warm-weather resort looks.",
    price: 180,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    ],
    category: "footwear",
    subcategory: "sandals",
    colors: ["beige", "brown"],
    materials: ["leather"],
    vibe: ["beach", "resort", "casual"],
    style: ["minimalist", "resort"],
    occasion: ["holiday", "beach club", "casual"],
    season: ["summer"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://aeyde.com/products/leather-slip-on-sandals",
    affiliateUrl: "https://socialmall.com/out/aeyde-sandals",
    retailer: "Aeyde",
    inStock: true,
    featured: false,
    popularityScore: 79,
    shippingCountry: "IE",
    brandSlug: "aeyde",
    productSlug: "leather-slip-on-sandals",
    rating: 4.5,
    reviewCount: 95,
  },
  {
    id: 7,
    brand: "Loulou Studio",
    name: "Silk Resort Shirt in Sand",
    description:
      "Silk resort shirt in a sand hue with fluid drape and relaxed tailoring for coastal evening styling.",
    price: 180,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80",
    ],
    category: "shirt",
    subcategory: "silk resort shirt",
    colors: ["beige", "cream"],
    materials: ["silk"],
    vibe: ["resort", "marbella", "elegant"],
    style: ["resort", "classy", "clean"],
    occasion: ["holiday", "dinner", "beach club"],
    season: ["summer", "spring"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://louloustudio.com/products/silk-resort-shirt-sand",
    affiliateUrl: null,
    retailer: "Loulou Studio",
    inStock: true,
    featured: false,
    popularityScore: 76,
    shippingCountry: "IE",
    brandSlug: "loulou-studio",
    productSlug: "silk-resort-shirt-sand",
    rating: 4.3,
    reviewCount: 68,
  },
  {
    id: 8,
    brand: "Levi's",
    name: "Blue Relaxed Straight Jeans",
    description:
      "Relaxed straight-fit jeans in classic blue denim for everyday streetwear and travel-ready outfits.",
    price: 95,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80",
    ],
    category: "jeans",
    subcategory: "straight jeans",
    colors: ["blue", "navy"],
    materials: ["denim", "cotton"],
    vibe: ["casual", "streetwear"],
    style: ["streetwear", "clean"],
    occasion: ["casual", "airport outfit"],
    season: ["autumn", "winter", "spring"],
    gender: ["unisex"],
    fit: ["relaxed", "baggy"],
    productUrl: "https://www.levi.com/products/relaxed-straight-jeans",
    affiliateUrl: "https://socialmall.com/out/levis-relaxed-jeans",
    retailer: "Levi's",
    inStock: true,
    featured: false,
    popularityScore: 91,
    compareAtPrice: 120,
    shippingCountry: "IE",
    brandSlug: "levis",
    productSlug: "blue-relaxed-straight-jeans",
    rating: 4.6,
    reviewCount: 1410,
  },
  {
    id: 9,
    brand: "Mango",
    name: "Open Knit Beach Club Dress",
    description:
      "Open-knit summer dress built for beach club layering with airy texture and holiday-ready movement.",
    price: 89.99,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    ],
    category: "dress",
    subcategory: "knit beach dress",
    colors: ["red"],
    materials: ["cotton", "knit"],
    vibe: ["marbella", "beach", "resort"],
    style: ["resort", "elegant"],
    occasion: ["beach club", "holiday", "party"],
    season: ["summer"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://shop.mango.com/open-knit-beach-club-dress",
    affiliateUrl: "https://socialmall.com/out/mango-beach-dress",
    retailer: "Mango",
    inStock: true,
    featured: true,
    popularityScore: 89,
    compareAtPrice: 109.99,
    shippingCountry: "IE",
    brandSlug: "mango",
    productSlug: "open-knit-beach-club-dress",
    rating: 4.4,
    reviewCount: 274,
  },
  {
    id: 10,
    brand: "Arket",
    name: "White Linen Wide-Leg Trousers",
    description:
      "Breathable linen trousers with a clean wide-leg silhouette ideal for summer tailoring and resort sets.",
    price: 120,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
    ],
    category: "trousers",
    subcategory: "linen trousers",
    colors: ["white", "cream"],
    materials: ["linen"],
    vibe: ["quiet luxury", "minimalist", "resort"],
    style: ["clean", "minimalist", "smart casual"],
    occasion: ["holiday", "office", "casual"],
    season: ["summer", "spring"],
    gender: ["women"],
    fit: ["wide leg", "relaxed"],
    productUrl: "https://www.arket.com/en/white-linen-wide-leg-trousers",
    affiliateUrl: "https://socialmall.com/out/arket-linen-trousers",
    retailer: "Arket",
    inStock: true,
    featured: true,
    popularityScore: 92,
    compareAtPrice: 149,
    shippingCountry: "IE",
    brandSlug: "arket",
    productSlug: "white-linen-wide-leg-trousers",
    rating: 4.7,
    reviewCount: 422,
  },
  {
    id: 11,
    brand: "Demellier",
    name: "Minimal Leather Shoulder Bag",
    description:
      "Structured leather shoulder bag with understated hardware designed for polished day-to-evening wear.",
    price: 360,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80",
    ],
    category: "bag",
    subcategory: "shoulder bag",
    colors: ["white", "beige"],
    materials: ["leather"],
    vibe: ["quiet luxury", "classy", "minimalist"],
    style: ["clean", "elegant", "minimalist"],
    occasion: ["office", "dinner", "formal"],
    season: ["autumn", "winter", "spring"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://demellierlondon.com/products/minimal-leather-shoulder-bag",
    affiliateUrl: "https://socialmall.com/out/demellier-shoulder-bag",
    retailer: "Demellier",
    inStock: false,
    featured: false,
    popularityScore: 74,
    shippingCountry: "IE",
    brandSlug: "demellier",
    productSlug: "minimal-leather-shoulder-bag",
    rating: 4.5,
    reviewCount: 181,
  },
  {
    id: 12,
    brand: "Mejuri",
    name: "Gold Everyday Hoop Earrings",
    description:
      "Lightweight polished hoop earrings for subtle daily styling and layered minimalist jewellery looks.",
    price: 110,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80",
    ],
    category: "jewellery",
    subcategory: "hoop earrings",
    colors: ["beige"],
    materials: ["gold"],
    vibe: ["minimalist", "elegant"],
    style: ["clean", "classy"],
    occasion: ["party", "dinner", "casual"],
    season: ["summer", "spring", "autumn"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://mejuri.com/products/gold-everyday-hoops",
    affiliateUrl: null,
    retailer: "Mejuri",
    inStock: true,
    featured: false,
    popularityScore: 71,
    shippingCountry: "IE",
    brandSlug: "mejuri",
    productSlug: "gold-everyday-hoop-earrings",
    rating: 4.4,
    reviewCount: 363,
  },
  {
    id: 13,
    brand: "Common Projects",
    name: "Minimal White Leather Sneakers",
    description:
      "Premium leather sneakers with understated branding and clean lines for elevated smart-casual wardrobes.",
    price: 430,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    ],
    category: "footwear",
    subcategory: "sneakers",
    colors: ["white"],
    materials: ["leather"],
    vibe: ["quiet luxury", "minimalist"],
    style: ["clean", "smart casual"],
    occasion: ["casual", "airport outfit", "office"],
    season: ["spring", "summer", "autumn"],
    gender: ["men"],
    fit: ["slim fit"],
    productUrl: "https://www.commonprojects.com/products/white-leather-sneakers",
    affiliateUrl: "https://socialmall.com/out/common-projects-sneakers",
    retailer: "Common Projects",
    inStock: true,
    featured: false,
    popularityScore: 85,
    shippingCountry: "IE",
    brandSlug: "common-projects",
    productSlug: "minimal-white-leather-sneakers",
    rating: 4.8,
    reviewCount: 294,
  },
  {
    id: 14,
    brand: "Uniqlo",
    name: "Black Cotton Oversized Tee",
    description:
      "Affordable oversized cotton tee with a clean silhouette designed for streetwear-inspired everyday layering.",
    price: 35,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1080&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    ],
    category: "tshirt",
    subcategory: "oversized t-shirt",
    colors: ["black"],
    materials: ["cotton"],
    vibe: ["streetwear", "casual"],
    style: ["streetwear", "clean"],
    occasion: ["casual", "gym", "airport outfit"],
    season: ["summer", "spring"],
    gender: ["unisex"],
    fit: ["oversized", "relaxed"],
    productUrl: "https://www.uniqlo.com/products/black-cotton-oversized-tee",
    affiliateUrl: "https://socialmall.com/out/uniqlo-oversized-tee",
    retailer: "Uniqlo",
    inStock: true,
    featured: true,
    popularityScore: 94,
    compareAtPrice: 45,
    shippingCountry: "IE",
    brandSlug: "uniqlo",
    productSlug: "black-cotton-oversized-tee",
    rating: 4.6,
    reviewCount: 1892,
  },
];
