import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: 1,
    brand: "The Row",
    name: "Cashmere Blend Wide-Leg Trousers",
    description:
      "Tailored wide-leg trousers in a soft cashmere-wool blend with a clean, elevated drape for quiet-luxury dressing.",
    price: 1190,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80",
    ],
    category: "trousers",
    subcategory: "wide-leg tailored trousers",
    colors: ["black"],
    materials: ["wool", "cashmere"],
    vibe: ["quiet luxury", "elegant", "minimalist"],
    style: ["minimalist", "clean", "classy"],
    occasion: ["dinner", "office", "formal"],
    season: ["winter", "autumn"],
    gender: ["women"],
    fit: ["wide leg", "tailored"],
    productUrl: "https://www.therow.com/products/cashmere-wide-leg-trousers",
    affiliateUrl: "https://socialmall.com/out/the-row-wide-leg-trousers",
    retailer: "The Row",
    inStock: true,
    featured: true,
    popularityScore: 97,
    shippingCountry: "IE",
    brandSlug: "the-row",
    productSlug: "cashmere-blend-wide-leg-trousers",
    rating: 4.8,
    reviewCount: 214,
  },
  {
    id: 2,
    brand: "Jacquemus",
    name: "Le Chouchou Draped Linen Shirt",
    description:
      "Lightweight draped linen shirt with a relaxed resort cut, ideal for summer evenings and smart-casual holiday looks.",
    price: 520,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80",
    ],
    category: "shirt",
    subcategory: "linen button-up shirt",
    colors: ["beige", "cream"],
    materials: ["linen"],
    vibe: ["marbella", "resort", "elegant"],
    style: ["resort", "smart casual", "minimalist"],
    occasion: ["holiday", "beach club", "dinner"],
    season: ["summer", "spring"],
    gender: ["men"],
    fit: ["relaxed"],
    productUrl: "https://www.jacquemus.com/products/le-chouchou-linen-shirt",
    affiliateUrl: "https://socialmall.com/out/jacquemus-linen-shirt",
    retailer: "Jacquemus",
    inStock: true,
    featured: true,
    popularityScore: 92,
    compareAtPrice: 590,
    shippingCountry: "IE",
    brandSlug: "jacquemus",
    productSlug: "le-chouchou-draped-linen-shirt",
    rating: 4.7,
    reviewCount: 161,
  },
  {
    id: 3,
    brand: "COS",
    name: "Relaxed Oversized Black Hoodie",
    description:
      "Heavyweight cotton hoodie with dropped shoulders and a clean oversized silhouette for casual streetwear layering.",
    price: 135,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=800&q=80",
    ],
    category: "hoodie",
    subcategory: "oversized pullover hoodie",
    colors: ["black"],
    materials: ["cotton", "knit"],
    vibe: ["casual", "streetwear", "minimalist"],
    style: ["streetwear", "clean"],
    occasion: ["airport outfit", "casual"],
    season: ["winter", "autumn"],
    gender: ["unisex"],
    fit: ["oversized", "relaxed"],
    productUrl: "https://www.cos.com/en/oversized-black-hoodie",
    affiliateUrl: "https://socialmall.com/out/cos-black-hoodie",
    retailer: "COS",
    inStock: true,
    featured: true,
    popularityScore: 95,
    compareAtPrice: 160,
    shippingCountry: "IE",
    brandSlug: "cos",
    productSlug: "relaxed-oversized-black-hoodie",
    rating: 4.6,
    reviewCount: 348,
  },
  {
    id: 4,
    brand: "Toteme",
    name: "Minimalist Structured Wool Blazer",
    description:
      "Sharp structured wool blazer with subtle waist definition for polished office and evening styling.",
    price: 790,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=800&q=80",
    ],
    category: "blazer",
    subcategory: "single-breasted blazer",
    colors: ["black"],
    materials: ["wool"],
    vibe: ["quiet luxury", "elegant", "minimalist"],
    style: ["classy", "smart casual", "minimalist"],
    occasion: ["office", "formal", "dinner"],
    season: ["winter", "autumn", "spring"],
    gender: ["women"],
    fit: ["tailored"],
    productUrl: "https://toteme.com/products/structured-wool-blazer",
    affiliateUrl: "https://socialmall.com/out/toteme-wool-blazer",
    retailer: "Toteme",
    inStock: true,
    featured: true,
    popularityScore: 90,
    shippingCountry: "IE",
    brandSlug: "toteme",
    productSlug: "minimalist-structured-wool-blazer",
    rating: 4.8,
    reviewCount: 133,
  },
  {
    id: 5,
    brand: "Arket",
    name: "White Cotton Essential Tee",
    description:
      "Soft jersey crew-neck tee with a relaxed cut and clean finish for daily capsule-wardrobe pairing.",
    price: 55,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    ],
    category: "tshirt",
    subcategory: "crew-neck tee",
    colors: ["white"],
    materials: ["cotton"],
    vibe: ["casual", "minimalist"],
    style: ["clean", "minimalist"],
    occasion: ["casual", "airport outfit"],
    season: ["summer", "spring"],
    gender: ["men"],
    fit: ["relaxed"],
    productUrl: "https://www.arket.com/en/cotton-essential-tee",
    affiliateUrl: "https://socialmall.com/out/arket-essential-tee",
    retailer: "Arket",
    inStock: true,
    featured: false,
    popularityScore: 84,
    compareAtPrice: 65,
    shippingCountry: "IE",
    brandSlug: "arket",
    productSlug: "white-cotton-essential-tee",
    rating: 4.4,
    reviewCount: 506,
  },
  {
    id: 6,
    brand: "Aeyde",
    name: "Leather Slip-On Sandals",
    description:
      "Minimal leather sandals with a low profile and easy slip-on shape built for warm-weather resort dressing.",
    price: 180,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    ],
    category: "footwear",
    subcategory: "flat sandals",
    colors: ["beige", "brown"],
    materials: ["leather"],
    vibe: ["beach", "resort", "casual"],
    style: ["minimalist", "resort"],
    occasion: ["holiday", "beach club", "casual"],
    season: ["summer"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://aeyde.com/products/leather-slip-on-sandals",
    affiliateUrl: "https://socialmall.com/out/aeyde-sandals",
    retailer: "Aeyde",
    inStock: true,
    featured: false,
    popularityScore: 81,
    shippingCountry: "IE",
    brandSlug: "aeyde",
    productSlug: "leather-slip-on-sandals",
    rating: 4.5,
    reviewCount: 94,
  },
  {
    id: 7,
    brand: "Loulou Studio",
    name: "Silk Resort Shirt in Sand",
    description:
      "Fluid silk shirt with a slightly oversized fit and tonal sand color, designed for elevated resort outfits.",
    price: 180,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=80",
    ],
    category: "shirt",
    subcategory: "silk resort shirt",
    colors: ["beige", "cream"],
    materials: ["silk"],
    vibe: ["resort", "marbella", "elegant"],
    style: ["resort", "classy", "clean"],
    occasion: ["holiday", "dinner", "beach club"],
    season: ["summer", "spring"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://louloustudio.com/products/silk-resort-shirt-sand",
    affiliateUrl: null,
    retailer: "Loulou Studio",
    inStock: true,
    featured: false,
    popularityScore: 79,
    shippingCountry: "IE",
    brandSlug: "loulou-studio",
    productSlug: "silk-resort-shirt-sand",
    rating: 4.3,
    reviewCount: 58,
  },
  {
    id: 8,
    brand: "Levi's",
    name: "Blue Relaxed Straight Jeans",
    description:
      "Classic straight-leg denim in a relaxed fit with vintage blue wash for everyday street and travel outfits.",
    price: 95,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    ],
    category: "jeans",
    subcategory: "straight-leg jeans",
    colors: ["blue", "navy"],
    materials: ["denim", "cotton"],
    vibe: ["casual", "streetwear"],
    style: ["streetwear", "clean"],
    occasion: ["casual", "airport outfit"],
    season: ["autumn", "winter", "spring"],
    gender: ["unisex"],
    fit: ["relaxed", "baggy"],
    productUrl: "https://www.levi.com/products/relaxed-straight-jeans",
    affiliateUrl: "https://socialmall.com/out/levis-relaxed-jeans",
    retailer: "Levi's",
    inStock: true,
    featured: false,
    popularityScore: 88,
    compareAtPrice: 115,
    shippingCountry: "IE",
    brandSlug: "levis",
    productSlug: "blue-relaxed-straight-jeans",
    rating: 4.6,
    reviewCount: 922,
  },
  {
    id: 9,
    brand: "Mango",
    name: "Open Knit Beach Club Dress",
    description:
      "Breathable open-knit dress in a vibrant red tone made for poolside layering and beach club evenings.",
    price: 89.99,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    ],
    category: "dress",
    subcategory: "knit cover-up dress",
    colors: ["red"],
    materials: ["cotton", "knit"],
    vibe: ["marbella", "beach", "resort"],
    style: ["resort", "elegant"],
    occasion: ["beach club", "holiday", "party"],
    season: ["summer"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://shop.mango.com/open-knit-beach-club-dress",
    affiliateUrl: "https://socialmall.com/out/mango-beach-dress",
    retailer: "Mango",
    inStock: true,
    featured: false,
    popularityScore: 86,
    compareAtPrice: 110,
    shippingCountry: "IE",
    brandSlug: "mango",
    productSlug: "open-knit-beach-club-dress",
    rating: 4.5,
    reviewCount: 207,
  },
  {
    id: 10,
    brand: "Arket",
    name: "White Linen Wide-Leg Trousers",
    description:
      "Breathable linen trousers with a wide-leg silhouette designed for summer tailoring and minimalist travel wardrobes.",
    price: 120,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    ],
    category: "trousers",
    subcategory: "linen wide-leg trousers",
    colors: ["white", "cream"],
    materials: ["linen"],
    vibe: ["quiet luxury", "minimalist", "resort"],
    style: ["clean", "minimalist", "smart casual"],
    occasion: ["holiday", "office", "casual"],
    season: ["summer", "spring"],
    gender: ["women"],
    fit: ["wide leg", "relaxed"],
    productUrl: "https://www.arket.com/en/white-linen-wide-leg-trousers",
    affiliateUrl: "https://socialmall.com/out/arket-linen-trousers",
    retailer: "Arket",
    inStock: true,
    featured: true,
    popularityScore: 89,
    shippingCountry: "IE",
    brandSlug: "arket",
    productSlug: "white-linen-wide-leg-trousers",
    rating: 4.6,
    reviewCount: 304,
  },
  {
    id: 11,
    brand: "Demellier",
    name: "Minimal Leather Shoulder Bag",
    description:
      "Structured leather shoulder bag with a quiet hardware finish, sized for day-to-night minimal outfits.",
    price: 360,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    ],
    category: "bag",
    subcategory: "shoulder bag",
    colors: ["white", "beige"],
    materials: ["leather"],
    vibe: ["quiet luxury", "classy", "minimalist"],
    style: ["clean", "elegant", "minimalist"],
    occasion: ["office", "dinner", "formal"],
    season: ["autumn", "winter", "spring"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://demellierlondon.com/products/minimal-leather-shoulder-bag",
    affiliateUrl: "https://socialmall.com/out/demellier-shoulder-bag",
    retailer: "Demellier",
    inStock: false,
    featured: false,
    popularityScore: 78,
    shippingCountry: "IE",
    brandSlug: "demellier",
    productSlug: "minimal-leather-shoulder-bag",
    rating: 4.4,
    reviewCount: 145,
  },
  {
    id: 12,
    brand: "Mejuri",
    name: "Gold Everyday Hoop Earrings",
    description:
      "Lightweight gold-tone hoops with a polished finish for subtle everyday styling from office to evening.",
    price: 110,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    category: "jewellery",
    subcategory: "hoop earrings",
    colors: ["beige"],
    materials: ["gold"],
    vibe: ["minimalist", "elegant"],
    style: ["clean", "classy"],
    occasion: ["party", "dinner", "casual"],
    season: ["summer", "spring", "autumn"],
    gender: ["women"],
    fit: ["relaxed"],
    productUrl: "https://mejuri.com/products/gold-everyday-hoops",
    affiliateUrl: null,
    retailer: "Mejuri",
    inStock: true,
    featured: false,
    popularityScore: 76,
    shippingCountry: "IE",
    brandSlug: "mejuri",
    productSlug: "gold-everyday-hoop-earrings",
    rating: 4.5,
    reviewCount: 602,
  },
  {
    id: 13,
    brand: "Common Projects",
    name: "Minimal White Leather Sneakers",
    description:
      "Premium leather low-top sneakers with understated branding and a clean smart-casual profile.",
    price: 430,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    ],
    category: "footwear",
    subcategory: "low-top sneakers",
    colors: ["white"],
    materials: ["leather"],
    vibe: ["quiet luxury", "minimalist"],
    style: ["clean", "smart casual"],
    occasion: ["casual", "airport outfit", "office"],
    season: ["spring", "summer", "autumn"],
    gender: ["men"],
    fit: ["slim fit"],
    productUrl: "https://www.commonprojects.com/products/white-leather-sneakers",
    affiliateUrl: "https://socialmall.com/out/common-projects-sneakers",
    retailer: "Common Projects",
    inStock: true,
    featured: false,
    popularityScore: 82,
    shippingCountry: "IE",
    brandSlug: "common-projects",
    productSlug: "minimal-white-leather-sneakers",
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: 14,
    brand: "Uniqlo",
    name: "Black Cotton Oversized Tee",
    description:
      "Budget-friendly oversized cotton tee with a heavy jersey feel and relaxed drape for casual layering.",
    price: 35,
    currency: "EUR",
    image:
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80",
    ],
    category: "tshirt",
    subcategory: "oversized crew-neck tee",
    colors: ["black"],
    materials: ["cotton"],
    vibe: ["streetwear", "casual"],
    style: ["streetwear", "clean"],
    occasion: ["casual", "gym", "airport outfit"],
    season: ["summer", "spring"],
    gender: ["unisex"],
    fit: ["oversized", "relaxed"],
    productUrl: "https://www.uniqlo.com/products/black-cotton-oversized-tee",
    affiliateUrl: "https://socialmall.com/out/uniqlo-oversized-tee",
    retailer: "Uniqlo",
    inStock: true,
    featured: true,
    popularityScore: 93,
    compareAtPrice: 45,
    shippingCountry: "IE",
    brandSlug: "uniqlo",
    productSlug: "black-cotton-oversized-tee",
    rating: 4.6,
    reviewCount: 1111,
  },
];
